networks:
  onlix:
    external: true

services:
  kong:
    build: ./kong
    container_name: onlix-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,kong-jwt2header  
    volumes:
      - ./kong/kong.yml:/kong/kong.yml:ro
    ports:
      - "8000:8000"   # Proxy
      - "8001:8001"   # Admin
    networks: 
      - onlix
